print(3+4)
print(3-4)
print(3*4)
print(3/4)
print(3+4)
print(16%4)#resto
print(18//4)
print(2**3) # potencia
print('hola' + 'cesar')
print(3+4*5/4+2*3)
print(3<4)
print(3>4)
print(3<=4)
print(3>=4)
print(3==4)
print(3!=4)# diferente
print(3!=4)
print(3!=4)

#operadores lógicos
print(4<5 and 5<6) # verdad y verdad = verdad
print(12<9 or 10<12) # verdad o falaso  = verdad
print(not(4<3))# negacion

