
my_condicion =25
if my_condicion == 10:
    print("se ejecuta el programa")
else:
    print('estamos ejecutando mal el programa')


my_condicional2 = 31
if my_condicional2>=15 and my_condicional2<=20:
    print("el valor esta bien")
elif my_condicional2!=31:
    print("el valor es uno")
else:
    print("esta mal el calculo, revisalo")


variab_x = 5
if variab_x == 8:
    print('no molestar')
else:
    print('friagate')    
